// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMnKGXml_QFMUABkJUGGDR1yMpx1kod20',
    appId: '1:924436629374:web:9947b6f88b952ea629d52f',
    messagingSenderId: '924436629374',
    projectId: 'app1-72f7f',
    authDomain: 'app1-72f7f.firebaseapp.com',
    storageBucket: 'app1-72f7f.firebasestorage.app',
    measurementId: 'G-ENBY8HF55M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBXcExt1_PWPY4zLRFfADTY9f5NVapqPo',
    appId: '1:924436629374:android:a248a55b7ed6de5e29d52f',
    messagingSenderId: '924436629374',
    projectId: 'app1-72f7f',
    storageBucket: 'app1-72f7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjPlUkRnNr0BSdhrE8G3ppVW-XYihfRi8',
    appId: '1:924436629374:ios:f0bdc5c0537af2b929d52f',
    messagingSenderId: '924436629374',
    projectId: 'app1-72f7f',
    storageBucket: 'app1-72f7f.firebasestorage.app',
    iosBundleId: 'com.example.travellingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjPlUkRnNr0BSdhrE8G3ppVW-XYihfRi8',
    appId: '1:924436629374:ios:f0bdc5c0537af2b929d52f',
    messagingSenderId: '924436629374',
    projectId: 'app1-72f7f',
    storageBucket: 'app1-72f7f.firebasestorage.app',
    iosBundleId: 'com.example.travellingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMnKGXml_QFMUABkJUGGDR1yMpx1kod20',
    appId: '1:924436629374:web:e9a61292187b84fb29d52f',
    messagingSenderId: '924436629374',
    projectId: 'app1-72f7f',
    authDomain: 'app1-72f7f.firebaseapp.com',
    storageBucket: 'app1-72f7f.firebasestorage.app',
    measurementId: 'G-CVP2MELCX5',
  );
}